IMG ?= iter8/iter8-trend:v0.2

docker-build:
	docker build . -t ${IMG}

docker-push:
	docker push ${IMG}

build-default:
	echo '# Generated by make build-default; DO NOT EDIT' > install/kubernetes/iter8-trend.yaml
	helm template install/kubernetes/helm/iter8-trend/ --name iter8-trend >> install/kubernetes/iter8-trend.yaml

.PHONY: test
test:
	./test/unit-test.sh
