IMG ?= haih/iter8-trend:latest

docker-build:
	docker build . -t ${IMG}

docker-push:
	docker push ${IMG}

build-default:
	echo '# Generated by make build-default; DO NOT EDIT' > install/kubernetes/iter8-trend.yaml
	helm template install/kubernetes/helm/iter8-trend/ --name iter8-trend >> install/kubernetes/iter8-trend.yaml

test:
	echo "This is a placeholder"
