{
 "title": "Iter8 trend",
 "time": { "from": "2020-04-28T01:10:43.476Z", "to": "2020-04-29T01:10:43.476Z" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(iter8_trend, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(iter8_trend, service_name)"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "label_values(iter8_trend, metric)"
   }
  ]
 },
 "panels": [
  {
   "title": "Experiment Metrics Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (max_over_time(iter8_trend{namespace='$namespace', service_name='$service', metric='$metric'}[7w])) by (time, metric) >= 0",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Iter8 Trend",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum (max_over_time(iter8_trend{namespace='$namespace', service_name='$service', metric='$metric'}[7w])) by (namespace, name, metric, time) >= 0"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(iter8_trend{namespace='$namespace', service_name='$service', metric='cpu'}[7w]) * 100 >= 0",
     "legendFormat": "{{time}}"
    }
   ]
  },
  {
   "title": "Average Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Bytes" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(iter8_trend{namespace='$namespace', service_name='$service', metric='mem'}[7w]) >= 0",
     "legendFormat": "{{time}}"
    }
   ]
  }
 ]
}